import type {
  NrrdSerializeOptions,
  NrrdVolume,
  ParsedNrrdHeader,
  ScalarVolume,
  ScalarVolumeMetadata,
} from "./types.js";

function createHeader(
  type: string,
  volume: NrrdVolume,
  options: NrrdSerializeOptions,
): string {
  const endian = options.endian ?? "little";
  const {
    metadata: { dimensions, spacing, origin, metadata },
  } = volume;
  const metadataEntries = Object.entries({
    ...(metadata ?? {}),
    ...(options.extraMetadata ?? {}),
  });
  const lines = [
    "NRRD0005",
    "# Generated by icc2sdf",
    `type: ${type}`,
    "dimension: 3",
    `sizes: ${dimensions.width} ${dimensions.height} ${dimensions.depth}`,
    `space directions: (${spacing.xStep},0,0) (0,${spacing.yStep},0) (0,0,${spacing.zStep})`,
    `space origin: (${origin.x},${origin.y},${origin.z})`,
    `endian: ${endian}`,
    "encoding: raw",
  ];

  for (const [key, value] of metadataEntries) {
    lines.push(`${key}:=${value}`);
  }

  return `${lines.join("\n")}\n\n`;
}

function concatHeaderAndData(header: string, bytes: Uint8Array): Uint8Array {
  const headerBytes = new TextEncoder().encode(header);
  const output = new Uint8Array(headerBytes.length + bytes.length);
  output.set(headerBytes, 0);
  output.set(bytes, headerBytes.length);
  return output;
}

function toBytes(view: ArrayBufferView): Uint8Array {
  return new Uint8Array(view.buffer, view.byteOffset, view.byteLength);
}

function splitHeaderAndData(bytes: Uint8Array): {
  header: string;
  dataOffset: number;
} {
  for (let index = 0; index < bytes.length - 1; index += 1) {
    if (bytes[index] === 0x0a && bytes[index + 1] === 0x0a) {
      const header = new TextDecoder().decode(bytes.subarray(0, index));
      return { header, dataOffset: index + 2 };
    }
  }

  throw new Error("Invalid NRRD payload: missing blank line after header");
}

function parseTuple3(value: string): [number, number, number] {
  const match = value
    .trim()
    .match(/^\(\s*([^,]+)\s*,\s*([^,]+)\s*,\s*([^)]+)\s*\)$/);
  if (match == null) {
    throw new Error(`Invalid 3D tuple: ${value}`);
  }

  return [Number(match[1]), Number(match[2]), Number(match[3])];
}

function parseSpaceDirections(value: string): Array<[number, number, number]> {
  const matches = Array.from(value.matchAll(/\([^)]+\)/g));
  return matches.map((match) => parseTuple3(match[0]));
}

export function parseNrrdHeader(headerText: string): ParsedNrrdHeader {
  const lines = headerText
    .split(/\r?\n/)
    .filter((line) => line.length > 0 && !line.startsWith("#"));
  if (lines[0] !== "NRRD0005") throw new Error("Unsupported NRRD magic");

  const fields = new Map<string, string>();
  const metadata: Record<string, string> = {};

  for (const line of lines.slice(1)) {
    const metadataIndex = line.indexOf(":=");
    if (metadataIndex >= 0) {
      metadata[line.slice(0, metadataIndex).trim()] = line
        .slice(metadataIndex + 2)
        .trim();
      continue;
    }

    const fieldIndex = line.indexOf(":");
    if (fieldIndex < 0) continue;

    fields.set(
      line.slice(0, fieldIndex).trim(),
      line.slice(fieldIndex + 1).trim(),
    );
  }

  const dimension = Number(fields.get("dimension"));
  const type = fields.get("type");
  const sizes = fields.get("sizes")?.split(/\s+/).map(Number);
  const encoding = fields.get("encoding");
  const endian = fields.get("endian");

  if (
    !Number.isInteger(dimension) ||
    type == null ||
    sizes == null ||
    encoding == null
  ) {
    throw new Error("NRRD header is missing required fields");
  }

  const parsedHeader: ParsedNrrdHeader = {
    dimension,
    type,
    sizes,
    encoding,
    metadata,
  };

  if (endian === "big" || endian === "little") parsedHeader.endian = endian;

  if (fields.has("space directions")) {
    parsedHeader.spaceDirections = parseSpaceDirections(
      fields.get("space directions")!,
    );
  }

  if (fields.has("space origin")) {
    parsedHeader.spaceOrigin = parseTuple3(fields.get("space origin")!);
  }

  return parsedHeader;
}

function createView(bytes: Uint8Array): Float32Array {
  const buffer = bytes.buffer.slice(
    bytes.byteOffset,
    bytes.byteOffset + bytes.byteLength,
  );
  return new Float32Array(buffer);
}

export function parseNrrd(bytes: Uint8Array): NrrdVolume {
  const { header, dataOffset } = splitHeaderAndData(bytes);
  const parsedHeader = parseNrrdHeader(header);

  if (parsedHeader.dimension !== 3) {
    throw new Error(
      `Only 3D NRRD volumes are supported, got dimension=${parsedHeader.dimension}`,
    );
  }

  if (parsedHeader.encoding !== "raw") {
    throw new Error(
      `Only raw NRRD encoding is supported, got ${parsedHeader.encoding}`,
    );
  }

  if (parsedHeader.type !== "float") {
    throw new Error(`Unsupported NRRD type: ${parsedHeader.type}`);
  }

  const data = createView(bytes.subarray(dataOffset));
  const directions = parsedHeader.spaceDirections;
  const origin = parsedHeader.spaceOrigin;

  if (directions == null || directions.length !== 3) {
    throw new Error("NRRD header is missing 3D space directions");
  }

  if (origin == null) {
    throw new Error("NRRD header is missing space origin");
  }

  const xDirection = directions[0];
  const yDirection = directions[1];
  const zDirection = directions[2];

  if (xDirection == null || yDirection == null || zDirection == null) {
    throw new Error("NRRD header is missing 3D space directions");
  }

  const metadata: ScalarVolumeMetadata = {
    dimensions: {
      width: parsedHeader.sizes[0] ?? 0,
      height: parsedHeader.sizes[1] ?? 0,
      depth: parsedHeader.sizes[2] ?? 0,
    },
    spacing: {
      xStep: xDirection[0],
      yStep: yDirection[1],
      zStep: zDirection[2],
    },
    origin: {
      x: origin[0],
      y: origin[1],
      z: origin[2],
    },
    metadata: parsedHeader.metadata,
  };

  return {
    metadata,
    data,
  };
}

export function serializeNrrd(
  volume: NrrdVolume,
  options: NrrdSerializeOptions = {},
): Uint8Array {
  const header = createHeader("float", volume, options);
  return concatHeaderAndData(header, toBytes(volume.data));
}

export function serializeScalarVolumeNrrd(
  volume: ScalarVolume<Float32Array>,
  options: NrrdSerializeOptions = {},
): Uint8Array {
  return serializeNrrd(volume, options);
}
